
# Syntax highlighting
markdown:            kramdown
highlighter:         pygments

# Permalinks
permalink:           pretty

# Setup
timezone:            New York
locale:              en_us
name:                Steve 
title:               site Steve
tagline:             'tagline'
description:         'description'
url:                 http://ppmanforthewin.github.io
rss:                 rss feed url
baseurl:             '/mickey/'
baseurl_posts_img:   '/mickey/assets/images/posts/'
baseurl_featured_img: '/mickey/assets/images/hero/'
baseurl_featured_thumbnail: '/mickey/assets/images/thumbnail/'
baseurl_javascripts: '/mickey/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              disqus_shortname # get it on https://disqus.com/admin/

author:
  name:           	 your name
  url:            	 your site url
  facebook:          username
  twitter:           username
  google_plus:       username
  linkedin:          username
  dribbble:          username
  pinterest:         username
  kiva:              username

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
